DELETE FROM USERS;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM ITEMS;
ALTER TABLE ITEMS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM BOOKINGS;
ALTER TABLE BOOKINGS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM COMMENTS;
ALTER TABLE COMMENTS ALTER COLUMN ID RESTART WITH 1;

--DELETE FROM STATUS;
--INSERT INTO STATUS (ID,CODE) VALUES (1,'WAITING'); -- НОВОЕ БРОНИРОВАНИЕ, ОЖИДАЕТ ОДОБРЕНИЯ
--INSERT INTO STATUS (ID,CODE) VALUES (2,'APPROVED'); -- БРОНИРОВАНИЕ ПОДТВЕРЖДЕНО ВЛАДЕЛЬЦЕМ
--INSERT INTO STATUS (ID,CODE) VALUES (3,'REJECTED'); -- БРОНИРОВАНИЕ ОТКЛОНЕНО ВЛАДЕЛЬЦЕМ
--INSERT INTO STATUS (ID,CODE) VALUES (4,'CANCELED'); -- БРОНИРОВАНИЕ ОТМЕНЕНО СОЗДАТЕЛЕМ


--ALTER TABLE USERS COLUMN ID RESTART SET START 1;
--TRUNCATE TABLE USERS RESTART IDENTITY
--ALTER SEQUENCE USERS_ID_SEQ RESTART WITH 1;